In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/messy_clinic_appointments.csv')
df.head(5)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          1000 non-null   int64
 1   patient_name        1000 non-null   object
 2   age                 1000 non-null   int64
 3   gender              950 non-null    object
 4   appointment_date    1000 non-null   object
 5   booking_date        1000 non-null   object
 6   doctor              1000 non-null   object
 7   department          1000 non-null   object
 8   billing_amount      950 non-null    object
 9   follow_up_required  1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.2+ KB

In [3]:
print('总记录数',len(df))
print('字段数量',len(df.columns))

总记录数 1000
字段数量 10

In [4]:
df.head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,M,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,M,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes

In [5]:
df.isna().sum()

patient_id             0
patient_name           0
age                    0
gender                50
appointment_date       0
booking_date           0
doctor                 0
department             0
billing_amount        50
follow_up_required     0
dtype: int64

In [6]:
df = df.replace(['N/A', 'NA', 'null', '', ' ', 'NULL'], np.nan)

In [7]:
df.head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,M,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,M,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes

In [8]:
df.head(20)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,M,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,M,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes
10,1086,Robert Guerrero,54,male,2025/04/24,07-Oct-2024,Shane Brown,Cardiology,£91.91,Y
11,1041,Karen Walker,68,F,2026/03/07,2024/04/24,Natalie White,General,$82.88,Yes
12,1057,Chris Rice,61,1,2025/07/31,"May 05, 24",Amy Olson,Neurology,Rs277.14,N
13,1022,Michael Mack,70,M,"September 21, 25",06-Nov-2024,John Larsen II,Orthopedics,€411.01,Y
14,1046,Andrea Hubbard,36,F,2026/03/12,11/08/2025,Andrea Gates,Cardiology,£67.51,N
15,1025,Brian Jones,23,female,06-Feb-2026,2025/03/09,Robert Navarro,Orthopedics,€163.99,Y
16,1027,Kelly Olsen,72,Male,"August 27, 25",13-Feb-2025,Christopher Bryant,Cardiology,£252.38,Yes
17,1059,Andrew Oconnor,66,Female,"November 11, 25",01-Dec-2024,Christina Hill,Cardiology,$153.07,Y
18,1086,Dennis Hurley,81,M,04/10/2025,2024/12/16,Daniel Jacobson,General,Rs329.3,1
19,1033,Paul Brock,76,Female,2025/11/05,2025/05/23,Kayla Savage,Neurology,€135.45,Yes

In [9]:
df.tail(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
990,1052,Nicholas Mcdaniel,48,F,"August 09, 25",2025/04/26,Daniel Smith,Orthopedics,€79.73,0
991,1075,Cheryl Rogers,43,M,01/12/2026,10/30/2025,Victoria Hansen,General,£376.76,Y
992,1047,Patricia Jackson,76,0,28-Feb-2026,11/19/2024,Jennifer Martin,Cardiology,Rs378.92,0
993,1017,Erin Bates,50,M,2025/06/13,15-Jan-2025,Chelsea Harris,Cardiology,$370.13,Y
994,1068,Aaron Holder,19,Male,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,Y
995,1082,Thomas Roman,64,Female,"September 14, 25",2024/07/15,Robert Bass,General,Rs200.43,Yes
996,1008,Jack Cooper,67,F,"April 09, 25","June 20, 24",Christopher Smith,General,Rs244.49,No
997,1022,Christopher Brown,28,1,"February 13, 26",2024/06/13,Kimberly Johnson,Neurology,£154.48,N
998,1088,Michael Sullivan,65,F,2025/07/04,2024/04/15,Anthony Mccoy,Neurology,$434.95,0
999,1003,Perry Crawford,79,Male,05-Nov-2025,2024/07/22,Marvin Hicks,Cardiology,€102.23,Y

In [10]:
df.tail(20)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
980,1028,Rebecca Franklin,43,0,"July 03, 25",2024/05/16,Daniel Love,Neurology,Rs187.7,1
981,1019,David Chapman,66,F,07/27/2025,"July 17, 25",Rachel Wells,Orthopedics,£382.67,No
982,1012,Timothy Fowler,78,female,"July 15, 25",04-Jul-2025,Donna Stephens,General,€236.27,0
983,1049,Megan Russell,84,Male,12/26/2025,07-Aug-2025,Autumn Hill,Cardiology,$359.17,Y
984,1081,Courtney Wright,43,NaN,26-Jul-2025,"May 24, 24",Daniel Morris,Orthopedics,Rs362.65,1
985,1045,Natalie Marquez,29,female,07/18/2025,"March 24, 25",Jennifer Paul,Neurology,£401.58,No
986,1076,Sarah Wilson,79,M,2026/02/21,"August 08, 24",Courtney Foley,Orthopedics,$120.7,Y
987,1047,Ashley Estes,54,1,2025/06/02,31-Jul-2024,Stephanie Mercer,Cardiology,£405.15,Yes
988,1068,William Bentley,42,Male,21-Oct-2025,2025/03/31,Jacob Mckay,Neurology,$263.3,Yes
989,1021,James Carey,41,1,03-Apr-2025,"August 22, 24",James Berger,Orthopedics,£470.08,1
990,1052,Nicholas Mcdaniel,48,F,"August 09, 25",2025/04/26,Daniel Smith,Orthopedics,€79.73,0
991,1075,Cheryl Rogers,43,M,01/12/2026,10/30/2025,Victoria Hansen,General,£376.76,Y
992,1047,Patricia Jackson,76,0,28-Feb-2026,11/19/2024,Jennifer Martin,Cardiology,Rs378.92,0
993,1017,Erin Bates,50,M,2025/06/13,15-Jan-2025,Chelsea Harris,Cardiology,$370.13,Y
994,1068,Aaron Holder,19,Male,2026/01/26,"November 28, 24",Lauren Ayers,General,Rs377.38,Y
995,1082,Thomas Roman,64,Female,"September 14, 25",2024/07/15,Robert Bass,General,Rs200.43,Yes
996,1008,Jack Cooper,67,F,"April 09, 25","June 20, 24",Christopher Smith,General,Rs244.49,No
997,1022,Christopher Brown,28,1,"February 13, 26",2024/06/13,Kimberly Johnson,Neurology,£154.48,N
998,1088,Michael Sullivan,65,F,2025/07/04,2024/04/15,Anthony Mccoy,Neurology,$434.95,0
999,1003,Perry Crawford,79,Male,05-Nov-2025,2024/07/22,Marvin Hicks,Cardiology,€102.23,Y

In [11]:
print(df.isnull().sum())

patient_id             0
patient_name           0
age                    0
gender                50
appointment_date       0
booking_date           0
doctor                 0
department             0
billing_amount        50
follow_up_required     0
dtype: int64

In [12]:
print(df.isnull().sum()/len(df)*100)

patient_id            0.0
patient_name          0.0
age                   0.0
gender                5.0
appointment_date      0.0
booking_date          0.0
doctor                0.0
department            0.0
billing_amount        5.0
follow_up_required    0.0
dtype: float64

In [13]:
df.head(5)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1

In [14]:
df.head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1
5,1057,Joe Sharp,78,1,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,M,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,M,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes

In [15]:
test=df

In [16]:
test.head()

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,1
1,1074,Megan Strickland,69,F,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Y
2,1067,Amanda Schroeder,79,M,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Y
3,1072,Anthony Mcpherson,47,F,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,NaN,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,1

In [17]:
print('gender 列的唯一值：')
print(test['gender'].unique())

gender 列的唯一值：
['female' 'F' 'M' nan '1' 'Female' 'male' 'Male' '0']

In [18]:
test['gender'].value_counts(dropna=False)

0         129
1         128
Male      123
Female    120
F         116
female    112
male      112
M         110
NaN        50
Name: gender, dtype: int64

In [19]:
test['follow_up_required'].unique()

array(['1', 'Y', 'No', 'Yes', 'N', '0'], dtype=object)

In [20]:
test['follow_up_required'].value_counts(dropna=False)

0      185
Y      182
Yes    181
N      154
1      151
No     147
Name: follow_up_required, dtype: int64

In [21]:
df['gender'] = df['gender'].astype(str).str.strip().str.lower()

gender_map_lower = {
    'Male': 'Male', 'M': 'Male', 'male': 'Male', '1': 'Male',
    'Female': 'Female', 'F': 'Female', 'female': 'Female', '0': 'Female'
}

df['gender'] = df['gender'].map(gender_map_lower).fillna('Unknown')

In [22]:
df['gender'].value_counts(dropna=False)

Male       363
Female     361
Unknown    276
Name: gender, dtype: int64

In [23]:
df['gender'].unique()

array(['Female', 'Unknown', 'Male'], dtype=object)

In [24]:
df['follow_up_required'] = df['follow_up_required'].astype(str).str.strip().str.lower()

followup_map_lower = {
    'yes': 'Yes', 'y': 'Yes', '1': 'Yes',
    'no': 'No', 'n': 'No', '0': 'No'
}
df['follow_up_required'] = df['follow_up_required'].map(followup_map_lower).fillna('No')

In [25]:
df.head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,Yes
1,1074,Megan Strickland,69,Unknown,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Yes
2,1067,Amanda Schroeder,79,Unknown,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Yes
3,1072,Anthony Mcpherson,47,Unknown,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,Unknown,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,Yes
5,1057,Joe Sharp,78,Male,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,Unknown,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,Female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,Unknown,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes

In [26]:
gender_mode = df['gender'].mode()[0] if not df['gender'].mode().empty else 'Unknown'
followup_mode = df['follow_up_required'].mode()[0] if not df['follow_up_required'].mode().empty else 'No'

In [27]:
print(gender_mode)
print(followup_mode)

Male
Yes

In [28]:
df['gender'].fillna(gender_mode,inplace=True)

df['follow_up_required'].fillna(followup_mode,inplace=True)

In [29]:
print(df['gender'].value_counts(dropna=False ))
print(df['follow_up_required'].value_counts(dropna=False))

Male       363
Female     361
Unknown    276
Name: gender, dtype: int64
Yes    514
No     486
Name: follow_up_required, dtype: int64

In [30]:
df.head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,Yes
1,1074,Megan Strickland,69,Unknown,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Yes
2,1067,Amanda Schroeder,79,Unknown,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Yes
3,1072,Anthony Mcpherson,47,Unknown,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,Unknown,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,Yes
5,1057,Joe Sharp,78,Male,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,Unknown,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,Female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,Unknown,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes

In [31]:
print("===== 当前数据类型 =====")
print(df.dtypes)

===== 当前数据类型 =====
patient_id             int64
patient_name          object
age                    int64
gender                object
appointment_date      object
booking_date          object
doctor                object
department            object
billing_amount        object
follow_up_required    object
dtype: object

In [32]:
print("\n===== 预约日期列样例 =====")
print(df['booking_date'].head(10))

===== 预约日期列样例 =====
0       2024/12/03
1      12-Jun-2024
2    August 05, 24
3       09/09/2024
4       08/17/2024
5       08/31/2025
6       12/29/2024
7      28-Mar-2025
8       2024/11/07
9      12-Dec-2025
Name: booking_date, dtype: object

In [33]:
print("\n===== 计费金额列样例 =====")
print(df['billing_amount'].head(10))

===== 计费金额列样例 =====
0      £425.8
1     €344.26
2     €203.34
3     Rs85.76
4      $84.44
5         NaN
6       €99.0
7    Rs374.63
8     $452.37
9     €494.97
Name: billing_amount, dtype: object

In [34]:
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values, sample: {df[col].unique()[:5]}")

patient_id: 101 unique values, sample: [1080 1074 1067 1072 1092]
patient_name: 988 unique values, sample: ['Tammy Williams' 'Megan Strickland' 'Amanda Schroeder'
 'Anthony Mcpherson' 'Benjamin Brown']
age: 73 unique values, sample: [76 69 79 47 45]
gender: 3 unique values, sample: ['Female' 'Unknown' 'Male']
appointment_date: 735 unique values, sample: ['2026/02/26' '05/23/2025' '30-Nov-2025' 'May 18, 25' '2026/03/07']
booking_date: 822 unique values, sample: ['2024/12/03' '12-Jun-2024' 'August 05, 24' '09/09/2024' '08/17/2024']
doctor: 990 unique values, sample: ['Christopher Graham' 'Brandon Lewis' 'Deanna Edwards' 'Karen Parsons'
 'Andrea Hernandez']
department: 4 unique values, sample: ['Cardiology' 'Orthopedics' 'Neurology' 'General']
billing_amount: 949 unique values, sample: ['£425.8' '€344.26' '€203.34' 'Rs85.76' '$84.44']
follow_up_required: 2 unique values, sample: ['Yes' 'No']

In [35]:
print(df.isnull().sum())
print(df.isnull().sum() / len(df) * 100)

patient_id             0
patient_name           0
age                    0
gender                 0
appointment_date       0
booking_date           0
doctor                 0
department             0
billing_amount        50
follow_up_required     0
dtype: int64
patient_id            0.0
patient_name          0.0
age                   0.0
gender                0.0
appointment_date      0.0
booking_date          0.0
doctor                0.0
department            0.0
billing_amount        5.0
follow_up_required    0.0
dtype: float64

In [36]:
df.index

RangeIndex(start=0, stop=1000, step=1)

In [37]:
print(df.index)

RangeIndex(start=0, stop=1000, step=1)

In [38]:
df.info

<bound method DataFrame.info of      patient_id       patient_name  age   gender  appointment_date  \
0          1080     Tammy Williams   76   Female        2026/02/26
1          1074   Megan Strickland   69  Unknown        05/23/2025
2          1067   Amanda Schroeder   79  Unknown       30-Nov-2025
3          1072  Anthony Mcpherson   47  Unknown        May 18, 25
4          1092     Benjamin Brown   45  Unknown        2026/03/07
..          ...                ...  ...      ...               ...
995        1082       Thomas Roman   64   Female  September 14, 25
996        1008        Jack Cooper   67  Unknown      April 09, 25
997        1022  Christopher Brown   28     Male   February 13, 26
998        1088   Michael Sullivan   65  Unknown        2025/07/04
999        1003     Perry Crawford   79     Male       05-Nov-2025

      booking_date              doctor   department billing_amount  \
0       2024/12/03  Christopher Graham   Cardiology         £425.8
1      12-Jun-2024       Brandon Lewis  Orthopedics        €344.26
2    August 05, 24      Deanna Edwards    Neurology        €203.34
3       09/09/2024       Karen Parsons      General        Rs85.76
4       08/17/2024    Andrea Hernandez      General         $84.44
..             ...                 ...          ...            ...
995     2024/07/15         Robert Bass      General       Rs200.43
996    June 20, 24   Christopher Smith      General       Rs244.49
997     2024/06/13    Kimberly Johnson    Neurology        £154.48
998     2024/04/15       Anthony Mccoy    Neurology        $434.95
999     2024/07/22        Marvin Hicks   Cardiology        €102.23

    follow_up_required
0                  Yes
1                  Yes
2                  Yes
3                   No
4                  Yes
..                 ...
995                Yes
996                 No
997                 No
998                 No
999                Yes

[1000 rows x 10 columns]>

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          1000 non-null   int64
 1   patient_name        1000 non-null   object
 2   age                 1000 non-null   int64
 3   gender              1000 non-null   object
 4   appointment_date    1000 non-null   object
 5   booking_date        1000 non-null   object
 6   doctor              1000 non-null   object
 7   department          1000 non-null   object
 8   billing_amount      950 non-null    object
 9   follow_up_required  1000 non-null   object
dtypes: int64(2), object(8)
memory usage: 78.2+ KB

In [40]:
df.head(10)

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,£425.8,Yes
1,1074,Megan Strickland,69,Unknown,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,€344.26,Yes
2,1067,Amanda Schroeder,79,Unknown,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,€203.34,Yes
3,1072,Anthony Mcpherson,47,Unknown,"May 18, 25",09/09/2024,Karen Parsons,General,Rs85.76,No
4,1092,Benjamin Brown,45,Unknown,2026/03/07,08/17/2024,Andrea Hernandez,General,$84.44,Yes
5,1057,Joe Sharp,78,Male,"September 26, 25",08/31/2025,Kimberly Fields,General,NaN,Yes
6,1018,Alexander Harris,22,Female,30-Oct-2025,12/29/2024,Jim Jones,Cardiology,€99.0,No
7,1074,Raymond Williams,57,Unknown,2025/04/23,28-Mar-2025,James Brooks,Neurology,Rs374.63,No
8,1041,Dustin Willis,54,Female,"August 22, 25",2024/11/07,Jamie Hill,General,$452.37,Yes
9,1011,Tina Gallagher,45,Unknown,03/16/2026,12-Dec-2025,Tiffany Gates MD,Neurology,€494.97,Yes

In [41]:
print("\n计费金额列的唯一值个数（样例）：", df['billing_amount'].nunique())
print(df['billing_amount'].unique()[:10])

计费金额列的唯一值个数（样例）： 949
['£425.8' '€344.26' '€203.34' 'Rs85.76' '$84.44' nan '€99.0' 'Rs374.63'
 '$452.37' '€494.97']

In [42]:
df['billing_amount'] = df['billing_amount'].astype(str)

In [43]:
df['billing_amount'] = df['billing_amount'].str.replace(r'[^0-9.]', '', regex=True)

In [44]:
print("\n清洗掉字符后的样例（前10个）：")
print(df['billing_amount'].head(10))

清洗掉字符后的样例（前10个）：
0     425.8
1    344.26
2    203.34
3     85.76
4     84.44
5
6      99.0
7    374.63
8    452.37
9    494.97
Name: billing_amount, dtype: object

In [45]:
df['billing_amount'] = pd.to_numeric(df['billing_amount'], errors='coerce')

In [46]:
print(f"\n转换后，计费金额列的空值数量: {df['billing_amount'].isna().sum()}")

转换后，计费金额列的空值数量: 50

In [47]:
median_billing = df['billing_amount'].median()
print(f"计费金额的中位数是: {median_billing}")

计费金额的中位数是: 269.84

In [48]:
df['billing_amount']=df['billing_amount'].fillna(median_billing)

In [49]:
print(f"填充后，计费金额列的空值数量: {df['billing_amount'].isna().sum()}")

填充后，计费金额列的空值数量: 0

In [50]:
print("\n===== 计费金额清洗完毕 =====")
print(df['billing_amount'].describe())
print(df['billing_amount'].head())

===== 计费金额清洗完毕 =====
count    1000.000000
mean      275.803030
std       126.833397
min        51.380000
25%       166.495000
50%       269.840000
75%       383.872500
max       499.750000
Name: billing_amount, dtype: float64
0    425.80
1    344.26
2    203.34
3     85.76
4     84.44
Name: billing_amount, dtype: float64

In [51]:
df.head()

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026/02/26,2024/12/03,Christopher Graham,Cardiology,425.80,Yes
1,1074,Megan Strickland,69,Unknown,05/23/2025,12-Jun-2024,Brandon Lewis,Orthopedics,344.26,Yes
2,1067,Amanda Schroeder,79,Unknown,30-Nov-2025,"August 05, 24",Deanna Edwards,Neurology,203.34,Yes
3,1072,Anthony Mcpherson,47,Unknown,"May 18, 25",09/09/2024,Karen Parsons,General,85.76,No
4,1092,Benjamin Brown,45,Unknown,2026/03/07,08/17/2024,Andrea Hernandez,General,84.44,Yes

In [52]:
print("===== 当前数据类型 =====")
print(df.dtypes)

===== 当前数据类型 =====
patient_id              int64
patient_name           object
age                     int64
gender                 object
appointment_date       object
booking_date           object
doctor                 object
department             object
billing_amount        float64
follow_up_required     object
dtype: object

In [53]:
print("\n===== 预约日期列样例 =====")
print(df['appointment_date'].head(10))

===== 预约日期列样例 =====
0          2026/02/26
1          05/23/2025
2         30-Nov-2025
3          May 18, 25
4          2026/03/07
5    September 26, 25
6         30-Oct-2025
7          2025/04/23
8       August 22, 25
9          03/16/2026
Name: appointment_date, dtype: object

In [54]:
df['appointment_date'] = pd.to_datetime(df['appointment_date'], errors='coerce')

df['booking_date'] = pd.to_datetime(df['booking_date'], errors='coerce')

In [55]:
failed_count = df['appointment_date'].isna().sum()
print(f"日期转换失败（变成空值）的数量: {failed_count}")

日期转换失败（变成空值）的数量: 0

In [56]:
print(f"\n日期范围: {df['appointment_date'].min()} 到 {df['appointment_date'].max()}")

日期范围: 2025-03-26 00:00:00 到 2026-03-26 00:00:00

In [57]:
initial_rows = len(df)
df.drop_duplicates(inplace=True)
print(f"1. 删除了 {initial_rows - len(df)} 行完全重复的数据")
print(f"   当前数据量: {len(df)} 行")

1. 删除了 0 行完全重复的数据
   当前数据量: 1000 行

In [58]:
duplicate_patients = df[df.duplicated(['patient_id'], keep=False)]
print(f"\n2. 有 {duplicate_patients['patient_id'].nunique()} 个患者有多次就诊记录（这是正常现象）")
print(f"   其中重复最多的患者就诊次数: {duplicate_patients['patient_id'].value_counts().max()} 次")

2. 有 101 个患者有多次就诊记录（这是正常现象）
   其中重复最多的患者就诊次数: 17 次

In [59]:
df.head()

,patient_id,patient_name,age,gender,appointment_date,booking_date,doctor,department,billing_amount,follow_up_required
0,1080,Tammy Williams,76,Female,2026-02-26,2024-12-03,Christopher Graham,Cardiology,425.80,Yes
1,1074,Megan Strickland,69,Unknown,2025-05-23,2024-06-12,Brandon Lewis,Orthopedics,344.26,Yes
2,1067,Amanda Schroeder,79,Unknown,2025-11-30,2024-08-05,Deanna Edwards,Neurology,203.34,Yes
3,1072,Anthony Mcpherson,47,Unknown,2025-05-18,2024-09-09,Karen Parsons,General,85.76,No
4,1092,Benjamin Brown,45,Unknown,2026-03-07,2024-08-17,Andrea Hernandez,General,84.44,Yes

In [60]:
print("\n===== 科室列清洗前 =====")
print("唯一值数量:", df['department'].nunique())
print("前20个唯一值样例:")
print(df['department'].unique()[:20])

===== 科室列清洗前 =====
唯一值数量: 4
前20个唯一值样例:
['Cardiology' 'Orthopedics' 'Neurology' 'General']

In [61]:
print("\n" + "="*50)
print("数据清洗最终验收报告")
print("="*50)

==================================================
数据清洗最终验收报告
==================================================

In [62]:
print(f"\n1. 最终数据量: {df.shape[0]} 行, {df.shape[1]} 列")

1. 最终数据量: 1000 行, 10 列

In [63]:
missing = df.isnull().sum()
print(f"\n2. 缺失值统计（期望全部为0）：")
print(missing[missing > 0])  # 只显示有缺失值的列
if missing.sum() == 0:
    print("   ✅ 所有列缺失值均为 0！")
else:
    print(f"   ⚠️ 还有 {missing.sum()} 个缺失值需要处理")

2. 缺失值统计（期望全部为0）：
Series([], dtype: int64)
   ✅ 所有列缺失值均为 0！

In [64]:
print(f"\n3. 数据类型：")
print(df.dtypes)

3. 数据类型：
patient_id                     int64
patient_name                  object
age                            int64
gender                        object
appointment_date      datetime64[ns]
booking_date          datetime64[ns]
doctor                        object
department                    object
billing_amount               float64
follow_up_required            object
dtype: object

In [65]:
print(f"\n4. 分类列唯一值检查：")
print(f"   gender: {df['gender'].unique()}")
print(f"   follow_up_required: {df['follow_up_required'].unique()}")
print(f"   department: {df['department'].nunique()} 个科室")

4. 分类列唯一值检查：
   gender: ['Female' 'Unknown' 'Male']
   follow_up_required: ['Yes' 'No']
   department: 4 个科室

In [66]:
print(f"\n5. 数值列统计概览：")
print(df[['age', 'billing_amount']].describe())

5. 数值列统计概览：
               age  billing_amount
count  1000.000000     1000.000000
mean     53.750000      275.803030
std      21.137604      126.833397
min      18.000000       51.380000
25%      34.000000      166.495000
50%      55.000000      269.840000
75%      71.000000      383.872500
max      90.000000      499.750000

In [67]:
df.to_csv('data/new_messy_clinic_appointments.csv', index=False)
print("\n✅ 清洗完成！文件已保存为 'new_messy_clinic_appointments.csv'")
print(f"   最终数据: {df.shape[0]} 行, {df.shape[1]} 列")

✅ 清洗完成！文件已保存为 'new_messy_clinic_appointments.csv'
   最终数据: 1000 行, 10 列